// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Ma Compta Simplifié

/**
 * Chart templates: semantic sources
 *
 * - **Association**: PCG général (ANC 2014-03 / art. 932-1) as the accounting backbone, plus
 *   accounts specific to **personnes morales à but non lucratif** set out in **ANC 2018-06**
 *   (contributions volontaires en nature — classe 8 / 86–87; nomenclature « ressources » 754–756…).
 *   Reference nomenclature: plan associations (livre III, art. 320-1 / 320-2 du règlement ANC 2018-06).
 *
 * - **TPE / entreprise**: **Plan comptable général** (petit périmètre utile TPE : stocks, TVA,
 *   achats/ventes courants, charges sociales, résultat).
 *
 * Numeric suffixes (e.g. four digits) follow usual PCG subdivisions; they are not invented labels.
 */

/** Association template — PCG (ANC 2014-03 art. 932-1) + comptes spécifiques art. 320-2 ANC 2018-06. */
export const PLAN_COMPTABLE_ASSOCIATION = [
  // Classe 1 — fonds propres, réserves, fonds dédiés (ANC 2018-06 art. 320-2 + PCG courant)
  { numero: '102', libelle: 'Fonds propres sans droit de reprise' },
  { numero: '1021', libelle: 'Première situation nette établie' },
  { numero: '1022', libelle: 'Fonds statutaires (à subdiviser en fonction des statuts)' },
  { numero: '1023', libelle: 'Dotations non consomptibles' },
  { numero: '10231', libelle: 'Dotations non consomptibles initiales' },
  { numero: '10232', libelle: 'Dotations non consomptibles complémentaires' },
  { numero: '1024', libelle: 'Autres fonds propres sans droit de reprise' },
  { numero: '103', libelle: 'Fonds propres avec droit de reprise' },
  { numero: '1032', libelle: 'Fonds statutaires (à subdiviser en fonction des statuts)' },
  { numero: '1034', libelle: 'Autres fonds propres avec droit de reprise' },
  { numero: '105', libelle: 'Ecarts de réévaluation' },
  { numero: '1051', libelle: 'Ecarts de réévaluation sur des biens sans droit de reprise' },
  { numero: '1052', libelle: 'Ecarts de réévaluation sur des biens avec droit de reprise' },
  { numero: '106', libelle: 'Réserves' },
  { numero: '1068', libelle: 'Réserves pour projet de l’entité' },
  { numero: '108', libelle: 'Dotations consomptibles' },
  { numero: '1081', libelle: 'Dotations consomptibles' },
  { numero: '1089', libelle: 'Dotations consomptibles inscrites au compte de résultat' },
  { numero: '110', libelle: 'Report à nouveau (solde créditeur)' },
  { numero: '119', libelle: 'Report à nouveau (solde débiteur)' },
  { numero: '120', libelle: "Résultat de l'exercice (bénéfice)" },
  { numero: '129', libelle: "Résultat de l'exercice (perte)" },
  { numero: '139', libelle: "Subventions d'investissement" },
  { numero: '152', libelle: 'Provisions pour charges sur legs ou donations' },
  { numero: '163', libelle: 'Autres emprunts obligataires' },
  { numero: '1631', libelle: 'Titres associatifs et assimilés' },
  { numero: '191', libelle: 'Fonds reportés liés aux legs ou donations' },
  { numero: '1911', libelle: 'Legs ou donations' },
  { numero: '1912', libelle: 'Donations temporaires d’usufruit' },
  { numero: '194', libelle: 'Fonds dédiés sur subventions d’exploitation' },
  { numero: '195', libelle: 'Fonds dédiés sur contributions financières d’autres organismes' },
  { numero: '196', libelle: 'Fonds dédiés sur ressources liées à la générosité du public' },

  // Classe 2 — immobilisations (PCG + art. 320-2)
  { numero: '24', libelle: 'Biens reçus par legs ou donations destinés à être cédés' },
  { numero: '204', libelle: 'Donations temporaires d’usufruit' },
  { numero: '211', libelle: 'Terrains' },
  { numero: '213', libelle: 'Constructions' },
  { numero: '215', libelle: 'Installations, matériel et outillage industriel' },
  { numero: '218', libelle: 'Autres immobilisations corporelles' },
  { numero: '2183', libelle: 'Matériel informatique' },
  { numero: '2742', libelle: 'Prêts aux partenaires' },
  { numero: '280', libelle: 'Amortissements des immobilisations incorporelles' },
  { numero: '2804', libelle: 'Donations temporaires d’usufruit' },
  { numero: '281', libelle: 'Amortissements des immobilisations corporelles' },
  { numero: '294', libelle: 'Dépréciations des biens reçus par legs ou donations destinés à être cédés' },

  // Classe 4 — tiers (PCG ; libellé adhérents ANC pour le 411)
  { numero: '401', libelle: 'Fournisseurs' },
  { numero: '411', libelle: 'Clients, adhérents, usagers et comptes rattachés' },
  { numero: '421', libelle: 'Personnel — rémunérations dues' },
  { numero: '431', libelle: 'Sécurité sociale' },
  { numero: '444', libelle: 'État — impôts sur les bénéfices' },
  { numero: '44566', libelle: 'TVA déductible sur autres biens et services' },
  { numero: '44571', libelle: 'TVA collectée' },
  { numero: '455', libelle: 'Partenaires - comptes courants' },
  { numero: '461', libelle: 'Créances reçues par legs ou donations' },
  { numero: '466', libelle: 'Dettes des legs ou donations' },
  { numero: '468', libelle: 'Divers charges à payer et produits à recevoir' },
  { numero: '4681', libelle: 'Frais des bénévoles' },

  // Classe 5 — financiers (PCG)
  { numero: '512', libelle: 'Banque' },
  { numero: '5122', libelle: 'Compte épargne / livret' },
  { numero: '530', libelle: 'Caisse' },

  // Classe 6 — charges (PCG ; subdivisions art. 320-2 et courantes)
  { numero: '601', libelle: 'Achats stockés — Matières premières (et fournitures)' },
  { numero: '602', libelle: 'Achats stockés — Autres approvisionnements' },
  { numero: '604', libelle: "Achats d'études et prestations de services" },
  { numero: '606', libelle: 'Achats non stockés de matières et fournitures' },
  { numero: '6061', libelle: 'Fournitures non stockables (eau, énergie, …)' },
  { numero: '6063', libelle: "Fournitures d'entretien et de petit équipement" },
  { numero: '6064', libelle: 'Fournitures administratives' },
  { numero: '6068', libelle: 'Autres matières et fournitures non stockées' },
  { numero: '607', libelle: 'Achats de marchandises' },
  { numero: '611', libelle: 'Sous-traitance générale' },
  { numero: '612', libelle: 'Redevances de crédit-bail' },
  { numero: '613', libelle: 'Locations' },
  { numero: '614', libelle: 'Charges locatives et de copropriété' },
  { numero: '615', libelle: 'Entretien et réparations' },
  { numero: '616', libelle: "Primes d'assurances" },
  { numero: '617', libelle: 'Études et recherches' },
  { numero: '618', libelle: 'Divers' },
  { numero: '6185', libelle: 'Frais de colloques, séminaires, conférences' },
  { numero: '621', libelle: "Personnel extérieur à l'entité" },
  { numero: '622', libelle: "Rémunérations d'intermédiaires et honoraires" },
  { numero: '6226', libelle: 'Honoraires' },
  { numero: '62264', libelle: 'Honoraires sur legs ou donations destinés à être cédés' },
  { numero: '623', libelle: 'Publicité, publications, relations publiques' },
  { numero: '624', libelle: 'Transports de biens et transports collectifs du personnel' },
  { numero: '625', libelle: 'Déplacements, missions et réceptions' },
  { numero: '6251', libelle: 'Voyages et déplacements' },
  { numero: '6256', libelle: 'Missions' },
  { numero: '6257', libelle: 'Réceptions' },
  { numero: '626', libelle: 'Frais postaux et de télécommunications' },
  { numero: '627', libelle: 'Services bancaires et assimilés' },
  { numero: '628', libelle: 'Divers' },
  { numero: '6281', libelle: 'Concours divers (cotisations, …)' },
  { numero: '631', libelle: 'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)' },
  { numero: '635', libelle: 'Autres impôts, taxes et versements assimilés (administrations des impôts)' },
  { numero: '641', libelle: 'Rémunérations du personnel' },
  { numero: '6411', libelle: 'Salaires, appointements' },
  { numero: '645', libelle: 'Charges de sécurité sociale et de prévoyance' },
  { numero: '647', libelle: 'Autres charges sociales' },
  { numero: '648', libelle: 'Autres charges de personnel' },
  { numero: '6511', libelle: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels' },
  { numero: '653', libelle: 'Charges de la générosité du public' },
  { numero: '6531', libelle: 'Autres charges sur legs ou donations' },
  { numero: '657', libelle: 'Aides financières' },
  { numero: '6571', libelle: 'Aides financières octroyées' },
  { numero: '6572', libelle: 'Quotes-parts de générosité reversée' },
  { numero: '658', libelle: 'Charges diverses de gestion courante' },
  { numero: '6718', libelle: 'Autres charges exceptionnelles sur opérations de gestion' },
  { numero: '673', libelle: 'Apports ou affectations en numéraire' },
  { numero: '675', libelle: 'Valeurs comptables des éléments d’actifs cédés' },
  { numero: '6754', libelle: 'Immobilisations reçues par legs ou donations' },
  { numero: '6788', libelle: 'Charges exceptionnelles diverses' },
  { numero: '681', libelle: 'Dotations aux amortissements, aux dépréciations et aux provisions' },
  { numero: '6816', libelle: 'Dotations pour dépréciations des immobilisations incorporelles et corporelles' },
  { numero: '68164', libelle: 'Dotations pour dépréciation d’actifs reçus par legs ou donations destinés à être cédés' },
  { numero: '689', libelle: 'Reports en fonds dédiés' },
  { numero: '6891', libelle: 'Reports en fonds reportés' },
  { numero: '6894', libelle: 'Reports en fonds dédiés sur subventions d’exploitation' },
  { numero: '6895', libelle: 'Reports en fonds dédiés sur contributions financières d’autres organismes' },
  { numero: '6896', libelle: 'Reports en fonds dédiés sur ressources liées à la générosité du public' },

  // Classe 7 — produits (PCG + rubriques « ressources » / legs ANC art. 320-2)
  { numero: '701', libelle: 'Ventes de produits finis' },
  { numero: '703', libelle: 'Ventes de produits résiduels' },
  { numero: '705', libelle: 'Études' },
  { numero: '706', libelle: 'Prestations de services' },
  { numero: '7063', libelle: 'Parrainages' },
  { numero: '707', libelle: 'Ventes de marchandises' },
  { numero: '7073', libelle: 'Ventes de dons en nature' },
  { numero: '708', libelle: 'Produits des activités annexes' },
  { numero: '7088', libelle: 'Autres produits des activités annexes (cessions approvisionnements, …)' },
  // Subventions classe 74 — ventilation PCG (même logique que 1311–1318 ; cf. plan comptable général ANC 2014-03)
  { numero: '740', libelle: "Subventions d'exploitation" },
  { numero: '7401', libelle: "Subventions d'exploitation — Etat" },
  { numero: '7402', libelle: "Subventions d'exploitation — Régions" },
  { numero: '7403', libelle: "Subventions d'exploitation — Départements" },
  { numero: '7404', libelle: "Subventions d'exploitation — Communes" },
  { numero: '7405', libelle: "Subventions d'exploitation — Collectivités publiques" },
  { numero: '7406', libelle: "Subventions d'exploitation — Entreprises publiques" },
  { numero: '7407', libelle: "Subventions d'exploitation — Entreprises et organismes privés" },
  { numero: '7408', libelle: "Subventions d'exploitation — Autres" },
  { numero: '741', libelle: "Subventions d'équilibre" },
  { numero: '7411', libelle: "Subventions d'équilibre — Etat" },
  { numero: '7412', libelle: "Subventions d'équilibre — Régions" },
  { numero: '7413', libelle: "Subventions d'équilibre — Départements" },
  { numero: '7414', libelle: "Subventions d'équilibre — Communes" },
  { numero: '7415', libelle: "Subventions d'équilibre — Collectivités publiques" },
  { numero: '7416', libelle: "Subventions d'équilibre — Entreprises publiques" },
  { numero: '7417', libelle: "Subventions d'équilibre — Entreprises et organismes privés" },
  { numero: '7418', libelle: "Subventions d'équilibre — Autres" },
  { numero: '742', libelle: 'Subventions des Communautés européennes' },
  { numero: '743', libelle: 'Subventions des organismes internationaux' },
  { numero: '744', libelle: "Autres subventions d'exploitation" },
  { numero: '748', libelle: 'Autres subventions' },
  { numero: '753', libelle: 'Versements des fondateurs ou consommation de la dotation' },
  { numero: '7531', libelle: 'Versements des fondateurs' },
  { numero: '7532', libelle: 'Quotes-parts de dotation consomptible virée au compte de résultat' },
  { numero: '754', libelle: 'Ressources liées à la générosité du public' },
  { numero: '7541', libelle: 'Dons manuels' },
  { numero: '75411', libelle: 'Dons manuels' },
  { numero: '75412', libelle: 'Abandons de frais par les bénévoles' },
  { numero: '7542', libelle: 'Mécénats' },
  { numero: '7543', libelle: 'Legs, donations et assurances-vie' },
  { numero: '75431', libelle: 'Assurances-vie' },
  { numero: '75432', libelle: 'Legs ou donations' },
  { numero: '75433', libelle: 'Autres produits sur legs ou donations' },
  { numero: '755', libelle: 'Contributions financières' },
  { numero: '7551', libelle: "Contributions financières d'autres organismes" },
  { numero: '7552', libelle: 'Quotes-parts de générosité reçues' },
  { numero: '756', libelle: 'Cotisations' },
  { numero: '7561', libelle: 'Cotisations sans contrepartie' },
  { numero: '7562', libelle: 'Cotisations avec contrepartie' },
  { numero: '757', libelle: 'Gains de change sur créances et dettes d’exploitation' },
  { numero: '758', libelle: 'Produits divers de gestion courante' },
  { numero: '760', libelle: 'Produits financiers' },
  { numero: '775', libelle: 'Produits des cessions d’éléments d’actifs' },
  { numero: '7754', libelle: 'Immobilisations reçues en legs ou donations destinées à être cédées' },
  {
    numero: '781',
    libelle:
      'Reprises sur amortissements des immobilisations dépréciations et provisions (à inscrire dans les produits d’exploitation)',
  },
  { numero: '7816', libelle: 'Reprises sur dépréciations des immobilisations incorporelles et corporelles' },
  {
    numero: '78164',
    libelle: 'Reprises sur dépréciations d’actifs reçus par legs ou donations destinés à être cédés',
  },
  { numero: '789', libelle: 'Utilisations de fonds reportés et de fonds dédiés' },
  { numero: '7891', libelle: 'Utilisations de fonds reportés' },
  { numero: '7894', libelle: 'Utilisations des fonds dédiés sur subventions d’exploitation' },
  { numero: '7895', libelle: 'Utilisations des fonds dédiés sur contributions financières d’autres organismes' },
  { numero: '7896', libelle: 'Utilisations des fonds dédiés sur ressources liées à la générosité du public' },

  // Classe 8 — contributions volontaires en nature (ANC 2018-06 — art. 320-2)
  { numero: '860', libelle: 'Secours en nature' },
  { numero: '861', libelle: 'Mises à disposition gratuites de biens' },
  { numero: '862', libelle: 'Prestations' },
  { numero: '864', libelle: 'Personnel bénévole' },
  { numero: '870', libelle: 'Dons en nature' },
  { numero: '871', libelle: 'Prestations en nature' },
  { numero: '875', libelle: 'Bénévolat' },
]

/** TPE — périmètre PCG général (entreprise), hors nomenclature associative ANC 2018-06. */
export const PLAN_COMPTABLE_TPE = [
  // Classe 1 — capitaux (PCG)
  { numero: '101', libelle: 'Capital' },
  { numero: '106', libelle: 'Réserves' },
  { numero: '110', libelle: 'Report à nouveau (solde créditeur)' },
  { numero: '119', libelle: 'Report à nouveau (solde débiteur)' },
  { numero: '120', libelle: "Résultat de l'exercice (bénéfice)" },
  { numero: '129', libelle: "Résultat de l'exercice (perte)" },

  // Classe 4 — tiers + TVA (PCG)
  { numero: '401', libelle: 'Fournisseurs' },
  { numero: '411', libelle: 'Clients' },
  { numero: '421', libelle: 'Personnel — rémunérations dues' },
  { numero: '431', libelle: 'Sécurité sociale' },
  { numero: '44566', libelle: 'TVA déductible sur autres biens et services' },
  { numero: '44571', libelle: 'TVA collectée' },

  // Classe 5
  { numero: '512', libelle: 'Banque' },
  { numero: '530', libelle: 'Caisse' },

  // Classe 6 — charges (PCG)
  { numero: '601', libelle: 'Achats stockés — Matières premières (et fournitures)' },
  { numero: '602', libelle: 'Achats stockés — Autres approvisionnements' },
  { numero: '604', libelle: "Achats d'études et prestations de services" },
  { numero: '606', libelle: 'Achats non stockés de matières et fournitures' },
  { numero: '6061', libelle: 'Fournitures non stockables (eau, énergie, …)' },
  { numero: '6063', libelle: "Fournitures d'entretien et de petit équipement" },
  { numero: '6064', libelle: 'Fournitures administratives' },
  { numero: '6068', libelle: 'Autres matières et fournitures non stockées' },
  { numero: '607', libelle: 'Achats de marchandises' },
  { numero: '611', libelle: 'Sous-traitance générale' },
  { numero: '613', libelle: 'Locations' },
  { numero: '614', libelle: 'Charges locatives et de copropriété' },
  { numero: '615', libelle: 'Entretien et réparations' },
  { numero: '616', libelle: "Primes d'assurances" },
  { numero: '617', libelle: 'Études et recherches' },
  { numero: '621', libelle: "Personnel extérieur à l'entreprise" },
  { numero: '6226', libelle: 'Honoraires' },
  { numero: '623', libelle: 'Publicité, publications, relations publiques' },
  { numero: '6251', libelle: 'Voyages et déplacements' },
  { numero: '626', libelle: 'Frais postaux et de télécommunications' },
  { numero: '627', libelle: 'Services bancaires et assimilés' },
  { numero: '6281', libelle: 'Concours divers (cotisations, …)' },
  { numero: '631', libelle: 'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)' },
  { numero: '635', libelle: 'Autres impôts, taxes et versements assimilés (administrations des impôts)' },
  { numero: '6411', libelle: 'Salaires, appointements' },
  { numero: '645', libelle: 'Charges de sécurité sociale et de prévoyance' },
  { numero: '648', libelle: 'Autres charges de personnel' },
  { numero: '6511', libelle: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels' },
  { numero: '658', libelle: 'Charges diverses de gestion courante' },
  { numero: '6718', libelle: 'Autres charges exceptionnelles sur opérations de gestion' },
  { numero: '6788', libelle: 'Charges exceptionnelles diverses' },
  { numero: '681', libelle: 'Dotations aux amortissements, aux dépréciations et aux provisions' },

  // Classe 7 — produits (PCG)
  { numero: '701', libelle: 'Ventes de produits finis' },
  { numero: '706', libelle: 'Prestations de services' },
  { numero: '707', libelle: 'Ventes de marchandises' },
  { numero: '708', libelle: 'Produits des activités annexes' },
  { numero: '7088', libelle: 'Autres produits des activités annexes (cessions approvisionnements, …)' },
  { numero: '740', libelle: "Subventions d'exploitation" },
  { numero: '7401', libelle: "Subventions d'exploitation — Etat" },
  { numero: '7402', libelle: "Subventions d'exploitation — Régions" },
  { numero: '7403', libelle: "Subventions d'exploitation — Départements" },
  { numero: '7404', libelle: "Subventions d'exploitation — Communes" },
  { numero: '7405', libelle: "Subventions d'exploitation — Collectivités publiques" },
  { numero: '7406', libelle: "Subventions d'exploitation — Entreprises publiques" },
  { numero: '7407', libelle: "Subventions d'exploitation — Entreprises et organismes privés" },
  { numero: '7408', libelle: "Subventions d'exploitation — Autres" },
  { numero: '741', libelle: "Subventions d'équilibre" },
  { numero: '7411', libelle: "Subventions d'équilibre — Etat" },
  { numero: '7412', libelle: "Subventions d'équilibre — Régions" },
  { numero: '7413', libelle: "Subventions d'équilibre — Départements" },
  { numero: '7414', libelle: "Subventions d'équilibre — Communes" },
  { numero: '7415', libelle: "Subventions d'équilibre — Collectivités publiques" },
  { numero: '7416', libelle: "Subventions d'équilibre — Entreprises publiques" },
  { numero: '7417', libelle: "Subventions d'équilibre — Entreprises et organismes privés" },
  { numero: '7418', libelle: "Subventions d'équilibre — Autres" },
  { numero: '742', libelle: 'Subventions des Communautés européennes' },
  { numero: '743', libelle: 'Subventions des organismes internationaux' },
  { numero: '744', libelle: "Autres subventions d'exploitation" },
  { numero: '748', libelle: 'Autres subventions' },
  { numero: '754', libelle: 'Ristournes perçues des coopératives (provenant des excédents)' },
  { numero: '758', libelle: 'Produits divers de gestion courante' },
]

export type ChartTemplateCode = 'ASSOCIATION' | 'TPE'

export function defaultAccountsForTemplate(code: ChartTemplateCode) {
  return code === 'TPE' ? PLAN_COMPTABLE_TPE : PLAN_COMPTABLE_ASSOCIATION
}
